### ISSUE TITLE
[Feature Request] Support Angular v18

### ISSUE THREAD

**Issue by shamoon** [amitdahan/ngx-filesize#469] opened 2024-06-13 22:13 UTC
I imagine this package is blocking the upgrade to v18 for some (us included) so would love to see this allow for v18. Thank you to the maintainers and contributors for your work.

https://github.com/amitdahan/ngx-filesize/blob/028b3ae78d212e805634dd3bf6ab30d365370b42/packages/ngx-filesize/package.json#L40-L42

**Comment by henk-van-der-vaart** [comment] 2024-06-26 11:07
The issue #471 seems a duplicate of this issue (feature request).
Also we experience blocking situation for upgrade to Angular 18 due to incompatibility with latest ngx-filesize 3.0.3 version.
Error seen 
_npm error Could not resolve dependency:
npm error peer @angular/common@">= 14.2.0 < 18.0.0" from ngx-filesize@3.0.3
npm error node_modules/ngx-filesize
npm error   ngx-filesize@"^3.0.3" from the root project_

So can this be picked up on short term please - would be highly appreciated.
Or otherwise is there an acceptable by-pass?

**Comment by amitdahan** [comment] 2024-07-11 13:12
https://github.com/amitdahan/ngx-filesize/issues/471#issuecomment-2222906550

**Closed by amitdahan** 2024-07-11 13:12 UTC
